### ISSUE TITLE
Library not found: libmetasec_ov.so

### ISSUE THREAD

**Issue by vanbac91** [iamtorsten/SherlockElf#1]
i always get the message
Library not found: libmetasec_ov.so
even though i can find this library via the File manager app

**Comment by iamtorsten** [comment]
@vanbac91 Which Plugin or example you tested?

Is your phone connected and Server is running on your phone?

**Comment by vanbac91** [comment]
i dont have an android phone to test on right now so i ran the server on a memu player emulator
i edited injector.py to make it work but got the above error

`import frida
import subprocess


class Inject:
    def __init__(self, target: str, is_emulator: bool = False):
        """
        Initialize the class with the target name or process ID.
        Set is_emulator to True if the target is an emulator.
        """
        self.target = target
        self.is_emulator = is_emulator

    def attach(self):
        """
        Attach to the target device or emulator.
        """
        device = frida.get_usb_device()

        if self.is_emulator:
            # Attach to the emulator process
            pid = self.get_emulator_pid()
            if not pid:
                raise Exception(f"Could not find the emulator: {self.target}")
            session = device.attach(pid)
        else:
            # Attach to a physical device using the package name or PID
            app = device.get_frontmost_application()
            if app:
                target_pid = app.pid
            else:
                target_pid = self.target
            session = device.attach(target_pid)

        return device, session

    def get_emulator_pid(self) -> int:
        """
        Get the process ID (PID) of the emulator using ADB.
        """
        result = subprocess.run(['adb', 'shell', 'ps'], stdout=subprocess.PIPE)
        processes = result.stdout.decode('utf-8').splitlines()

        for process in processes:
            if self.target in process:
                return int(process.split()[1])

        return None

    def source(self, session, code):
        """
        Inject JavaScript code into the Frida session.
        """
        return session.create_script(code)`

**Comment by iamtorsten** [comment]
Is the App on Emulator started before executing the Injector?

**Comment by iamtorsten** [comment]
@vanbac91 please reopen if the problem occurs again.
